services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    restart: unless-stopped
    init: true
    ports:
      - "8000:8000"  # Django development server
    env_file: ./.env  
    volumes:  
       - ./media:/app/media
       - ./db.sqlite3:/app/db.sqlite3
       - ./staticfiles:/app/staticfiles
    command: >
      sh -c "python manage.py collectstatic --noinput && \
             ls -l /app/staticfiles && \
             python manage.py migrate && \
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - appnet
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - python-app
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
