# Generated by Django 5.2.1 on 2025-06-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='articles/')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('auteur', models.CharField(max_length=50)),
                ('contenu', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
