# Generated by Django 5.0.6 on 2025-06-05 09:04

from django.db import migrations

def create_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('blog', 'Profile')
    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
